
; Custom Dialplan for 57 prefix with CallerID Override
[default]
exten => _57XXXXXXXX.,1,NoOp(Checking ForceCID: ${ForceCID})
exten => _57XXXXXXXX.,n,GotoIf($["${ForceCID}" != ""]?setmanual)
exten => _57XXXXXXXX.,n,AGI(callerid_local_presence.agi)
exten => _57XXXXXXXX.,n,GotoIf($["${CID}" != ""]?gotcid)
exten => _57XXXXXXXX.,n,NoOp(AGI returned empty - Using Campaign Default)
exten => _57XXXXXXXX.,n,Goto(dial)

exten => _57XXXXXXXX.,n(setmanual),Set(CID=${ForceCID})
exten => _57XXXXXXXX.,n,Goto(gotcid)

exten => _57XXXXXXXX.,n(gotcid),NoOp(Using Pool CID: ${CID})
exten => _57XXXXXXXX.,n,Set(CALLERID(num)=${CID})
exten => _57XXXXXXXX.,n,Set(CALLERID(name)=${CID})
exten => _57XXXXXXXX.,n,SipAddHeader(P-Asserted-Identity: <sip:${CID}@209.38.233.46>)
exten => _57XXXXXXXX.,n(dial),Dial(SIP/sbc233/1122${EXTEN})
exten => _57XXXXXXXX.,n,Hangup()
