
; Custom Dialplan for 57 prefix
exten => _57XXXXXXXX.,1,AGI(callerid_local_presence.agi)
exten => _57XXXXXXXX.,n,GotoIf($["${CID}" != ""]?gotcid)
exten => _57XXXXXXXX.,n,NoOp(AGI returned empty - Using Campaign Default)
exten => _57XXXXXXXX.,n,Goto(dial)
exten => _57XXXXXXXX.,n(gotcid),NoOp(Using Pool CID: ${CID})
exten => _57XXXXXXXX.,n,Set(CALLERID(num)=57)
exten => _57XXXXXXXX.,n,Set(CALLERID(name)=57)
exten => _57XXXXXXXX.,n,SipAddHeader(P-Asserted-Identity: <sip:57@209.38.233.46>)
exten => _57XXXXXXXX.,n(dial),Dial(SIP/sbc233/1122)
exten => _57XXXXXXXX.,n,Hangup()
