const express = require('express');
const router = express.Router();
const fs = require('fs');
const path = require('path');
const { exec } = require('child_process');

module.exports = (pg) => {

    const PJSIP_CONF_PATH = '/etc/asterisk/pjsip-gescall.conf';
    const ASTERISK_MAIN_CONF = '/etc/asterisk/pjsip.conf';

    // Helper to regenerate PJSIP file
    async function regeneratePjsipConf() {
        try {
            const { rows } = await pg.query('SELECT * FROM gescall_trunks WHERE active = true');

            let confContent = '; AUTOGENERATED BY GESCALL - DO NOT EDIT MANUALLY\n\n';

            for (const trunk of rows) {
                const tName = trunk.trunk_name;

                // 1. Registration (if enabled)
                if (trunk.registration) {
                    confContent += `[${tName}]\n`;
                    confContent += `type=registration\n`;
                    confContent += `transport=transport-udp\n`;
                    confContent += `outbound_auth=${tName}_auth\n`;
                    confContent += `server_uri=sip:${trunk.provider_host}:${trunk.provider_port}\n`;
                    confContent += `client_uri=sip:${trunk.auth_user}@${trunk.provider_host}:${trunk.provider_port}\n`;
                    confContent += `retry_interval=60\n`;
                    confContent += `expiration=3600\n`;
                    confContent += `line=yes\n`;
                    confContent += `endpoint=${tName}\n\n`;
                }

                // 2. Auth
                if (trunk.auth_user) {
                    confContent += `[${tName}_auth]\n`;
                    confContent += `type=auth\n`;
                    confContent += `auth_type=userpass\n`;
                    confContent += `username=${trunk.auth_user}\n`;
                    confContent += `password=${trunk.auth_password}\n\n`;
                }

                // 3. AOR
                confContent += `[${tName}]\n`;
                confContent += `type=aor\n`;
                confContent += `contact=sip:${trunk.provider_host}:${trunk.provider_port}\n`;
                confContent += `qualify_frequency=60\n\n`;

                // 4. Endpoint
                confContent += `[${tName}]\n`;
                confContent += `type=endpoint\n`;
                confContent += `transport=transport-udp\n`;
                confContent += `context=trunkinbound\n`;
                confContent += `disallow=all\n`;
                confContent += `allow=${trunk.codecs || 'ulaw,alaw'}\n`;
                if (trunk.auth_user) {
                    confContent += `outbound_auth=${tName}_auth\n`;
                }
                confContent += `aors=${tName}\n`;
                // NAT settings often needed for trunks
                confContent += `direct_media=no\n`;
                confContent += `force_rport=yes\n`;
                confContent += `rtp_symmetric=yes\n`;
                confContent += `rewrite_contact=yes\n\n`;

                // 5. Identify (for inbound calls)
                confContent += `[${tName}]\n`;
                confContent += `type=identify\n`;
                confContent += `endpoint=${tName}\n`;
                confContent += `match=${trunk.provider_host}\n\n`;
            }

            fs.writeFileSync(PJSIP_CONF_PATH, confContent);

            // Ensure pjsip.conf includes our file
            let mainConf = fs.readFileSync(ASTERISK_MAIN_CONF, 'utf8');
            if (!mainConf.includes('#include pjsip-gescall.conf')) {
                mainConf = '#include pjsip-gescall.conf\n' + mainConf;
                fs.writeFileSync(ASTERISK_MAIN_CONF, mainConf);
            }

            // Reload PJSIP in Asterisk
            exec('asterisk -rx "pjsip reload"', (err, stdout, stderr) => {
                if (err) console.error('[Trunks] Error reloading PJSIP:', err);
                else console.log('[Trunks] PJSIP reloaded successfully.');
            });

            return true;
        } catch (error) {
            console.error('[Trunks] Error generating PJSIP conf:', error);
            return false;
        }
    }

    // Get trunk statuses from Asterisk PJSIP
    router.get('/status', (req, res) => {
        exec('asterisk -rx "pjsip show contacts"', (err, stdout) => {
            if (err) {
                console.error('[Trunks] Error fetching pjsip contacts:', err);
                return res.status(500).json({ error: 'Failed to read trunk statuses' });
            }

            const statusMap = {};
            const lines = stdout.split('\n');

            for (const line of lines) {
                if (line.trim().startsWith('Contact:  ')) {
                    // e.g. Contact:  sbc233/sip:190.242.45.3:5060                   040ee3bc24 Avail        81.331
                    const parts = line.trim().split(/\s+/);
                    if (parts.length >= 5) {
                        const aor = parts[1].split('/')[0];
                        const status = parts[3];
                        const rtt = parts[4];
                        statusMap[aor] = { status, rtt };
                    }
                }
            }

            // Also check 'pjsip show endpoints' to find 'Not in use' or 'In use'
            // but for latency and 'Avail' state, contacts is sufficient.
            res.json(statusMap);
        });
    });

    // Get all trunks
    router.get('/', async (req, res) => {
        try {
            const { rows } = await pg.query('SELECT * FROM gescall_trunks ORDER BY trunk_name ASC');
            res.json(rows);
        } catch (error) {
            console.error('[API] Error fetching trunks:', error);
            res.status(500).json({ error: 'Internal server error' });
        }
    });

    // Create trunk
    router.post('/', async (req, res) => {
        const { trunk_id, trunk_name, provider_host, provider_port, auth_user, auth_password, registration, max_channels, max_cps, dial_prefix, codecs, active } = req.body;

        try {
            await pg.query(`
                INSERT INTO gescall_trunks 
                (trunk_id, trunk_name, provider_host, provider_port, auth_user, auth_password, registration, max_channels, max_cps, dial_prefix, codecs, active)
                VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
            `, [trunk_id, trunk_name, provider_host, provider_port || 5060, auth_user, auth_password, registration !== false, max_channels || 50, max_cps != null ? max_cps : 50, dial_prefix, codecs || 'ulaw,alaw', active !== false]);

            await regeneratePjsipConf();
            res.json({ message: 'Trunk created successfully' });
        } catch (error) {
            console.error('[API] Error creating trunk:', error);
            res.status(500).json({ error: error.message });
        }
    });

    // Update trunk
    router.put('/:id', async (req, res) => {
        const { id } = req.params;
        const { trunk_name, provider_host, provider_port, auth_user, auth_password, registration, max_channels, max_cps, dial_prefix, codecs, active } = req.body;

        try {
            await pg.query(`
                UPDATE gescall_trunks SET 
                trunk_name=$1, provider_host=$2, provider_port=$3, auth_user=$4, auth_password=$5, 
                registration=$6, max_channels=$7, max_cps=$8, dial_prefix=$9, codecs=$10, active=$11, updated_at=NOW()
                WHERE trunk_id=$12
            `, [trunk_name, provider_host, provider_port || 5060, auth_user, auth_password, registration, max_channels, max_cps, dial_prefix, codecs, active, id]);

            await regeneratePjsipConf();
            res.json({ message: 'Trunk updated successfully' });
        } catch (error) {
            console.error('[API] Error updating trunk:', error);
            res.status(500).json({ error: 'Internal server error' });
        }
    });

    // Delete trunk
    router.delete('/:id', async (req, res) => {
        const { id } = req.params;
        try {
            await pg.query('DELETE FROM gescall_trunks WHERE trunk_id=$1', [id]);
            await regeneratePjsipConf();
            res.json({ message: 'Trunk deleted successfully' });
        } catch (error) {
            console.error('[API] Error deleting trunk:', error);
            res.status(500).json({ error: 'Internal server error' });
        }
    });

    // Manual reload trigger
    router.post('/reload', async (req, res) => {
        const success = await regeneratePjsipConf();
        if (success) {
            res.json({ message: 'PJSIP Configuration regenerated and reloaded' });
        } else {
            res.status(500).json({ error: 'Failed to reload configuration' });
        }
    });

    return router;
};
