const pg = require('../config/pgDatabase');
const fs = require('fs');
const { exec } = require('child_process');

async function main() {
    console.log("Starting regeneration...");
    const PJSIP_CONF_PATH = '/etc/asterisk/pjsip-gescall.conf';
    const ASTERISK_MAIN_CONF = '/etc/asterisk/pjsip.conf';

    const { rows } = await pg.query('SELECT * FROM gescall_trunks WHERE active = true');

    let confContent = '; AUTOGENERATED BY GESCALL - DO NOT EDIT MANUALLY\n\n';

    for (const trunk of rows) {
        const tName = trunk.trunk_name;

        // 1. Registration (if enabled)
        if (trunk.registration) {
            confContent += `[${tName}]\n`;
            confContent += `type=registration\n`;
            confContent += `transport=transport-udp\n`;
            confContent += `outbound_auth=${tName}_auth\n`;
            confContent += `server_uri=sip:${trunk.provider_host}:${trunk.provider_port}\n`;
            confContent += `client_uri=sip:${trunk.auth_user}@${trunk.provider_host}:${trunk.provider_port}\n`;
            confContent += `retry_interval=60\n`;
            confContent += `expiration=3600\n`;
            confContent += `line=yes\n`;
            confContent += `endpoint=${tName}\n\n`;
        }

        // 2. Auth
        if (trunk.auth_user) {
            confContent += `[${tName}_auth]\n`;
            confContent += `type=auth\n`;
            confContent += `auth_type=userpass\n`;
            confContent += `username=${trunk.auth_user}\n`;
            confContent += `password=${trunk.auth_password}\n\n`;
        }

        // 3. AOR
        confContent += `[${tName}]\n`;
        confContent += `type=aor\n`;
        confContent += `contact=sip:${trunk.provider_host}:${trunk.provider_port}\n`;
        confContent += `qualify_frequency=60\n\n`;

        // 4. Endpoint
        confContent += `[${tName}]\n`;
        confContent += `type=endpoint\n`;
        confContent += `transport=transport-udp\n`;
        confContent += `context=trunkinbound\n`;
        confContent += `disallow=all\n`;
        confContent += `allow=${trunk.codecs || 'ulaw,alaw'}\n`;
        if (trunk.auth_user) {
            confContent += `outbound_auth=${tName}_auth\n`;
        }
        confContent += `aors=${tName}\n`;
        // NAT settings often needed for trunks
        confContent += `direct_media=no\n`;
        confContent += `force_rport=yes\n`;
        confContent += `rtp_symmetric=yes\n`;
        confContent += `rewrite_contact=yes\n\n`;

        // 5. Identify (for inbound calls)
        confContent += `[${tName}]\n`;
        confContent += `type=identify\n`;
        confContent += `endpoint=${tName}\n`;
        confContent += `match=${trunk.provider_host}\n\n`;
    }

    fs.writeFileSync(PJSIP_CONF_PATH, confContent);
    console.log("Wrote PJSIP Conf to", PJSIP_CONF_PATH);

    let mainConf = fs.readFileSync(ASTERISK_MAIN_CONF, 'utf8');
    if (!mainConf.includes('#include pjsip-gescall.conf')) {
        mainConf = '#include pjsip-gescall.conf\n' + mainConf;
        fs.writeFileSync(ASTERISK_MAIN_CONF, mainConf);
    }

    console.log("Reloading Asterisk PJSIP...");
    exec('asterisk -rx "pjsip reload"', (err) => {
        if (err) console.error(err);
        else console.log('Done!');
        process.exit(0);
    });
}

main().catch(console.error);
