const pg = require('../config/pgDatabase');
const fs = require('fs');
const { exec } = require('child_process');
const crypto = require('crypto');

async function syncUsers() {
    try {
        console.log('[Sync] Finding users without extensions...');
        const { rows: users } = await pg.query("SELECT user_id, username FROM gescall_users WHERE sip_extension IS NULL OR sip_extension = ''");
        
        const extRes = await pg.query("SELECT MAX(sip_extension::integer) as max_ext FROM gescall_users WHERE sip_extension ~ '^[0-9]+$'");
        let newExtension = extRes.rows[0].max_ext ? parseInt(extRes.rows[0].max_ext) : 999;

        for (const user of users) {
            newExtension++;
            const pass = crypto.randomBytes(6).toString('hex');
            await pg.query('UPDATE gescall_users SET sip_extension = $1, sip_password = $2 WHERE user_id = $3', [newExtension.toString(), pass, user.user_id]);
            console.log(`[Sync] Assigned ${newExtension} to ${user.username}`);
        }

        console.log('[Sync] Regenerating Asterisk PJSIP users config...');
        const { rows: activeUsers } = await pg.query("SELECT sip_extension, sip_password FROM gescall_users WHERE active = true AND sip_extension IS NOT NULL");
        
        let confContent = '; AUTOGENERATED BY GESCALL USERS API - DO NOT EDIT MANUALLY\n\n';
        for (const user of activeUsers) {
            const ext = user.sip_extension;
            const pass = user.sip_password;
            
            confContent += `[${ext}]\n`;
            confContent += `type=endpoint\n`;
            confContent += `context=from-internal\n`;
            confContent += `disallow=all\n`;
            confContent += `allow=ulaw,alaw\n`;
            confContent += `auth=${ext}\n`;
            confContent += `aors=${ext}\n`;
            confContent += `direct_media=no\n`;
            confContent += `force_rport=yes\n`;
            confContent += `rtp_symmetric=yes\n`;
            confContent += `rewrite_contact=yes\n`;
            confContent += `webrtc=yes\n`;
            confContent += `dtls_auto_generate_cert=yes\n`;
            confContent += `dtls_verify=fingerprint\n`;
            confContent += `ice_support=yes\n`;
            confContent += `use_avpf=yes\n`;
            confContent += `media_encryption=dtls\n`;
            confContent += `media_use_received_transport=yes\n\n`;

            confContent += `[${ext}]\n`;
            confContent += `type=auth\n`;
            confContent += `auth_type=userpass\n`;
            confContent += `password=${pass}\n`;
            confContent += `username=${ext}\n\n`;

            confContent += `[${ext}]\n`;
            confContent += `type=aor\n`;
            confContent += `max_contacts=2\n\n`;
        }
        
        fs.writeFileSync('/etc/asterisk/pjsip_gescall_users.conf', confContent);
        
        let mainConf = fs.readFileSync('/etc/asterisk/pjsip.conf', 'utf8');
        if (!mainConf.includes('#include pjsip_gescall_users.conf')) {
            mainConf += '\\n#include pjsip_gescall_users.conf\\n';
            fs.writeFileSync('/etc/asterisk/pjsip.conf', mainConf);
        }

        exec('asterisk -rx "pjsip reload"', (err) => {
            if (err) console.error('[Sync] Error reloading PJSIP:', err);
            else {
                console.log('[Sync] PJSIP reloaded successfully.');
                process.exit(0);
            }
        });

    } catch(err) {
        console.error('[Sync] Error:', err);
        process.exit(1);
    }
}

syncUsers();
