/**
 * Regenera /etc/asterisk/pjsip_gescall_users.conf desde PostgreSQL y recarga PJSIP.
 * Debe ejecutarse tras cualquier cambio a sip_extension / sip_password de agentes.
 */
const fs = require('fs');
const dotenv = require('dotenv');
const { exec } = require('child_process');

const envPath = `${__dirname}/../.env`;
if (fs.existsSync(envPath)) {
    const envConfig = dotenv.parse(fs.readFileSync(envPath));
    for (const k in envConfig) {
        process.env[k] = envConfig[k];
    }
}

const pg = require('../config/pgDatabase');

async function regeneratePjsipGescallUsers() {
    try {
        const { rows } = await pg.query(
            'SELECT sip_extension, sip_password FROM gescall_users WHERE active = true AND sip_extension IS NOT NULL'
        );
        let confContent =
            '; AUTOGENERATED BY GESCALL USERS API - DO NOT EDIT MANUALLY\n\n';
        for (const user of rows) {
            const ext = String(user.sip_extension ?? '').trim();
            const pass = user.sip_password != null ? String(user.sip_password) : '';
            if (!ext) continue;

            const sid = ext.replace(/[^a-zA-Z0-9]/g, '_');
            const authObj = `gescall-${sid}-auth`;
            const aorObj = ext;

            // El endpoint debe llamarse como la extensión para que PJSIP resuelva el REGISTER.
            confContent += `[${ext}]\n`;
            confContent += `type=endpoint\n`;
            confContent += `context=from-internal\n`;
            confContent += `disallow=all\n`;
            confContent += `allow=ulaw,alaw\n`;
            confContent += `auth=${authObj}\n`;
            confContent += `aors=${aorObj}\n`;
            confContent += `direct_media=no\n`;
            confContent += `force_rport=yes\n`;
            confContent += `rtp_symmetric=yes\n`;
            confContent += `rewrite_contact=yes\n`;
            confContent += `webrtc=yes\n`;
            confContent += `dtls_auto_generate_cert=yes\n`;
            confContent += `dtls_verify=fingerprint\n`;
            confContent += `ice_support=yes\n`;
            confContent += `use_avpf=yes\n`;
            confContent += `media_encryption=dtls\n`;
            confContent += `media_use_received_transport=yes\n\n`;

            confContent += `[${authObj}]\n`;
            confContent += `type=auth\n`;
            confContent += `auth_type=userpass\n`;
            confContent += `password=${pass}\n`;
            confContent += `username=${ext}\n\n`;

            confContent += `[${aorObj}]\n`;
            confContent += `type=aor\n`;
            confContent += `max_contacts=2\n\n`;
        }

        fs.writeFileSync('/etc/asterisk/pjsip_gescall_users.conf', confContent);

        let mainConf = fs.readFileSync('/etc/asterisk/pjsip.conf', 'utf8');
        if (!mainConf.includes('#include pjsip_gescall_users.conf')) {
            mainConf += '\n#include pjsip_gescall_users.conf\n';
            fs.writeFileSync('/etc/asterisk/pjsip.conf', mainConf);
        }

        exec('asterisk -rx "pjsip reload"', (err) => {
            if (err) console.error('[PJSIP-Gescall-Users] Error reloading PJSIP:', err);
            else console.log('[PJSIP-Gescall-Users] PJSIP reloaded successfully.');
        });
    } catch (err) {
        console.error('[PJSIP-Gescall-Users] Error generating PJSIP users conf:', err);
    }
}

module.exports = { regeneratePjsipGescallUsers };
